import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KOBITO BASE",
  description: "Generated by KOBITO BASE",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <head>
        <meta name="google-site-verification" content="xxxxxxxxxxxxxxxxxxxx" />
      </head>
      <body>{children}</body>
    </html>
  );
}
